spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_verification
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
jwt:
  secret-key: "Secret Key"
  expiration: 3600 # JWT 토큰 만료 시간 (초 단위)

